#pragma once

#define COMBO_VARIABLE_LEN
#undef COMBO_TERM
#define COMBO_TERM 30

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 3
#define AUTO_MOUSE_TIME 750

#define IGNORE_MOD_TAP_INTERRUPT
// #define PERMISSIVE_HOLD
// #undef IGNORE_MOD_TAP_INTERRUPT
#undef PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPPING_TERM 120
#define FP_SUPER_TAB_TIMEOUT 1000

// #define CIRQUE_PINNACLE_TAPPING_TERM 0
// #define CIRQUE_PINNACLE_TOUCH_DEBOUNCE 0
// #define CIRQUE_PINNACLE_DIAMETER_MM 35

// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define ONESHOT_TIMEOUT 1000
