#pragma once

#define COMBO_VARIABLE_LEN
#undef COMBO_TERM
#define COMBO_TERM 30

// #ifdef FP_POINTING_DEFAULT_DPI
//     #undef FP_POINTING_DEFAULT_DPI
//     #define FP_POINTING_DEFAULT_DPI 800
// #endif
// #define FP_POINTING_SCROLLING_DPI 10
// #define FP_POINTING_ACCELERATION_ENABLE

// #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// #define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 2
// #define AUTO_MOUSE_DEFAULT_LAYER 3
// #define AUTO_MOUSE_TIME 2500
// #define AUTO_MOUSE_DELAY 750

// #define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPPING_TERM 100
#define FP_SUPER_TAB_TIMEOUT 750
#define ONESHOT_TIMEOUT 750

#define FP_POINTING_ACCELERATION_ENABLE

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_LAYERS_RETAIN_VAL
#define FP_STARTUP_ANIMATION_DISABLE
#define FP_LAYER_LIGHTING_HUE_1 HSV_CYAN
#define FP_LAYER_LIGHTING_MODE_1 RGBLIGHT_MODE_BREATHING
#define FP_LAYER_LIGHTING_HUE_2 FP_HSV_LAVENDER
#define FP_LAYER_LIGHTING_MODE_2 RGBLIGHT_MODE_BREATHING
#define FP_LAYER_LIGHTING_HUE_3 FP_HSV_MELON
#define FP_LAYER_LIGHTING_MODE_3 RGBLIGHT_MODE_BREATHING
#define FP_LAYER_LIGHTING_CAPS_LOCK_MODE RGBLIGHT_MODE_KNIGHT
#endif