name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: sadekbaroudi/qmk_firmware
        ref: develop_fingerpunch
        # ref: develop_qmk
        submodules: true

    - name: Checkout keymap
      uses: actions/checkout@v3
      with:
        path: keyboards/fingerpunch/ffkb_byomcu/v3/keymaps/${{ github.actor }}

    - name: Build firmware (Trackball)
      run: make fingerpunch/ffkb_byomcu/v3:${{ github.actor }} FP_TRACKBALL_ENABLE=yes CONVERT_TO=stemcell
    - name: Archive firmware (Trackball)
      uses: actions/upload-artifact@v3
      with:
        name: ffkb_v3_${{ github.actor }}_trackball
        retention-days: 5
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

    - name: Build firmware (Cirque)
      run: make fingerpunch/ffkb_byomcu/v3:${{ github.actor }} CIRQUE_ENABLE=yes CONVERT_TO=stemcell
    - name: Archive firmware (Cirque)
      uses: actions/upload-artifact@v3
      with:
        name: ffkb_v3_${{ github.actor }}_cirque
        retention-days: 5
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

    - name: Build firmware (Both)
      run: make fingerpunch/ffkb_byomcu/v3:${{ github.actor }} CIRQUE_ENABLE=yes FP_TRACKBALL_ENABLE=yes CONVERT_TO=stemcell
    - name: Archive firmware (Both)
      uses: actions/upload-artifact@v3
      with:
        name: ffkb_v3_${{ github.actor }}_trackball-cirque
        retention-days: 5
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
